// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Corridor struct {
	ID         string `json:"id"`
	CorridorID string `json:"corridor_id"`
	Name       string `json:"name"`
	From       *Halte `json:"from"`
	To         *Halte `json:"to"`
}

type Halte struct {
	ID      string `json:"id"`
	HalteID string `json:"halte_id"`
	Name    string `json:"name"`
}

type Mutation struct {
}

type NewCorridor struct {
	Name        string `json:"name"`
	FromHalteID string `json:"from_halte_id"`
	ToHalteID   string `json:"to_halte_id"`
}

type NewHalte struct {
	Name string `json:"name"`
}

type NewSubway struct {
	Name       string `json:"name"`
	CorridorID string `json:"corridor_id"`
}

type Query struct {
}

type Subway struct {
	ID       string    `json:"id"`
	SubwayID string    `json:"subway_id"`
	Name     string    `json:"name"`
	Corridor *Corridor `json:"corridor"`
}
